---
name: "build-and-publish"
run-name: "Pubishing latest push by ${{ github.actor }}"
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v4

      # Install deps
      - uses: actions/setup-node@v4
        with:
          node-version: 16
          cache: "npm"
      - run: "npm install"

        # Build HTML
      - run: "mv src/pages/* public/"

        # Build SCSS
      - run: "npm run build-scss"

        # Build Typescrpt
      - run: "npm run build-ts"

        # bundle
      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v3
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: ./public

  publish:
    runs-on: ubuntu-latest
    # the artifact must already be built with the name github-pages
    needs: build
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
